
ASMFLAGS += -ffreestanding -nostdinc -nostdlib -nostartfiles
CFLAGS += -ffreestanding -nostdlib -nostartfiles

KERNEL_ARCH_OBJS= \
$(BUILDDIR)/$(ARCHDIR)/boot.o \
$(BUILDDIR)/$(ARCHDIR)/delay.o \
$(BUILDDIR)/$(ARCHDIR)/exceptions.o \
$(BUILDDIR)/$(ARCHDIR)/exc_handler.o \
$(BUILDDIR)/$(ARCHDIR)/executionLevel.o \
$(BUILDDIR)/$(ARCHDIR)/gpfio.o \
$(BUILDDIR)/$(ARCHDIR)/init.o \
$(BUILDDIR)/$(ARCHDIR)/kuart.o \
$(BUILDDIR)/$(ARCHDIR)/mbox.o \
$(BUILDDIR)/$(ARCHDIR)/vga.o \
$(BUILDDIR)/$(ARCHDIR)/pmem.o
