
ASMFLAGS += -ffreestanding -nostdinc -nostdlib -nostartfiles
CFLAGS += -ffreestanding -nostdlib -nostartfiles

KERNEL_ARCH_OBJS= \
$(BUILDDIR)/$(ARCHDIR)/boot.o \
$(BUILDDIR)/$(ARCHDIR)/kuart.o \
$(BUILDDIR)/$(ARCHDIR)/gpfio.o